= Listeners

*Событие* (Event) - это то, что произошло. В мире веб-приложений событием может быть инициализация приложения, уничтожение приложения, запрос от клиента, создание / уничтожение сеанса, изменение атрибутов в сеансе и т. Д.

Servlet API предоставляет различные типы интерфейсов слушателей, которые мы можем реализовать и настроить в web.xml для обработки определенных событий, когда происходят определенные события. Например, в приведенном выше сценарии мы могли бы создать прослушиватель для события запуска приложения, чтобы прочитать параметры инициализации контекста и создать соединение с базой данных, а также установить его как свойство контекста для использования другими ресурсами.

== Интерфейс Servlet Listener и объект Event

*Servlet API* предоставляет разные типы слушателей для разных типов событий. Интерфейс слушателя объявляет методы для обработки подобного набора событий.Например, у нас есть прослушиватель `ServletContext`, который прослушивает события запуска и завершения контекста. Каждый метод в интерфейсе слушателя принимает объект события в качестве входных данных. Объект события действует как оболочка, предоставляя конкретный объект для слушателя.

*Servlet API* предоставляет следующие объекты событий:

* `javax.servlet.AsyncEvent`- событие, которое вызывается, когда асинхронная операция, инициированная `ServletRequest` (путем вызова `ServletRequest` # `startAsync` или `ServletRequest` # `startAsync (ServletRequest, ServletResponse))`, завершилась по тайм-ауту или вызвала ошибку.
* `javax.servlet.http.HttpSessionBindingEvent` - отправьте событие этого типа объекту, который реализует `HttpSessionBindingListener`, когда объект связан или не связан с сеансом, или `HttpSessionAttributeListener`, настроенному в `web.xml`, когда любой атрибут связан , Отвязать или заменить в сеансе. Сеанс связывает объект, вызывая `HttpSession.setAttribute`, и отменяет привязку объекта, вызывая `HttpSession.removeAttribute`. Когда объект удаляется из сеанса, мы можем использовать это событие для операций очистки.
* `javax.servlet.http.HttpSessionEvent` - это класс, который представляет уведомления о событиях изменения сеанса в веб-приложении.
* `javax.servlet.ServletContextAttributeEvent` - класс событий для уведомлений об изменениях атрибутов `ServletContext` веб-приложения.
* `javax.servlet.ServletContextEvent`- это класс событий для уведомлений об изменениях контекста сервлета веб-приложения.
* `javax.servlet.ServletRequestEvent`- этот тип события представляет событие жизненного цикла `ServletRequest`. Исходный код события - `ServletContext` этого веб-приложения.
* `javax.servlet.ServletRequestAttributeEvent`- это класс событий для уведомления об изменениях атрибутов, запрошенных сервлетом в приложении.

*Servlet API* предоставляет следующие интерфейсы слушателя:

* `javax.servlet.AsyncListener`- слушатель будет уведомлен, если асинхронная операция, запущенная в ServletRequest с добавленным слушателем, завершилась, истекло время ожидания или вызвала ошибку.
* `javax.servlet.ServletContextListener`- интерфейс для получения уведомлений об изменениях жизненного цикла ServletContext.
* `javax.servlet.ServletContextAttributeListener`- интерфейс, который получает события уведомления об изменениях атрибута ServletContext.
* `javax.servlet.ServletRequestListener`- интерфейс для получения событий уведомления о запросах, входящих и выходящих из области веб-приложения.
* `javax.servlet.ServletRequestAttributeListener`- интерфейс, который получает события уведомления об изменениях атрибута ServletRequest.
* `javax.servlet.http.HttpSessionListener`- интерфейс для получения уведомлений об изменениях жизненного цикла HttpSession.
* `javax.servlet.http.HttpSessionBindingListener`- приводит к уведомлению объекта, когда он связан с или из сеанса.
* `javax.servlet.http.HttpSessionAttributeListener`- интерфейс для получения событий уведомления об изменениях атрибута HttpSession.
* `javax.servlet.http.HttpSessionActivationListener`-Objects, привязанные к сеансу, могут прослушивать события контейнера, сообщая им, что сеанс будет пассивирован и что сеанс будет активирован. Контейнер сеанса необходимо перенести между виртуальными машинами или постоянными сеансами, чтобы уведомить все свойства, связанные с сеансом, который реализует HttpSessionActivationListener.

== Настройка Servlet Listener

Mожно использовать аннотацию `@WebListener` для объявления класса как `Listener`, но класс должен реализовывать один или несколько интерфейсов `Listener`.

Mожно определить слушателей в `web.xml`:

[source, xml]
----
<listener>
    <listener-class>
        com.journaldev.listener.AppContextListener
    </listener-class>
</listener>
----
