= `CallableStatement`

Подобно тому, как объект `Connection` создает объекты `Statement` и `PreparedStatement`, он также создает объект `CallableStatement`, который будет использоваться для выполнения вызова хранимой процедуры из базы данных. *Хранимая процедура* - последовательность команд, хранимых в *БД*.

Синтаксис вызова хранимой процедуры в `JDBC` показан ниже. Квадратные скобки означают, что параметры необязательны и сами по себе не являются частью синтаксиса.

[source, java]
----
{call имя_процедуры[(?, ?, ...)]}

{? = call имя_процедуры[(?, ?, ...)]}

{call имя_процедуры}
----

== Создание объекта `CallableStatement`

Объекты `CallableStatement` создаются методом `prepareCall` объекта `Connection`. Пример, который создает экземпляр `CallableStatement`, содержащий вызов хранимой процедуры с двумя аргументами и без возвращаемого параметра:

[source, java]
----
CallableStatement cstmt = con.prepareCall("{call procedure_name(?, ?)}");
----

== Входные и выходные `IN` и `OUT`-параметры

Для передачи и получения значения из хранимой процедуры есть три типа параметров:  `IN`, `OUT` и `INOUT`. Объект `CallableStatement` может использовать все три.

|===
|*Параметры*|*Описание*
|`IN`|Параметр, значение которого присваивается по умолчанию при создании оператора `SQL`. C помощью метода `setXXX()` можно установить входные значения с параметром `IN`.
|`OUT`|Параметр, значение которого предоставляется оператором `SQL`, который он возвращает. Извлечение значения из параметров `OUT` выполнется с помощью методов `getXXX()`.
|`INOUT`|Параметр, который предоставляет как входные, так и выходные значения. Можно связать переменные с помощью методов `setXXX()` и извлекаете значения с помощью методов `getXXX()`.
|===

Передача значений входных парметров объекта `CallableStatement` осуществляется с помощью методов `setXXX`, унаследованных от `PreparedStatement`. Типы передаваемых значений определяются тем, какой из методов `setXXX` используется (`setString` для передачи значений типа `String`, `setInt` для передачи значений типа `int` и т.п.).

`JDBC`-типы всех `OUT`-параметров хранимых процедур должны быть зарегистрированы перед их вызовом. Регистрация типов данных выходного параметра производится методом `registerOutParameter`. Только в этом случае после вызова хранимой процедуры `CallableStatement.executeQuery()` можно получить результаты выполнения с помощью методов `getXXX`. Необходимо использовать подходящий по типу данных метод `getXXX` в соответствии с зарегистрированным `JDBC`-типом параметра.

Другими словами, `registerOutParameter` использует `JDBC`-тип, который подходит к `JDBC`-типу возвращаемого из значения, а `getXXX` преобразует его в тип Java.

Пример регистрации выходных параметров хранимой процедуры и чтение выходных значений.

[source, java]
----
CallableStatement cstmt = con.prepareCall ("{call getData(?, ?)}");
cstmt.registerOutParameter(1, java.sql.Types.TINYINT);
cstmt.registerOutParameter(2, java.sql.Types.DECIMAL, 2);
// Вызов хранимой процедуры
cstmt.executeQuery();
// Чтение выходных данных
byte x = cstmt.getByte(1);
java.math.BigDecimal n = cstmt.getBigDecimal(2, 2);
----

В примере метод `getByte` извлекает байт из первого выходного параметра, а `getBigDecimal` возвращает объект `BigDecimal` (с двумя цифрами после десятичной точки) из второго выходного параметра.

Если параметр является одновременно и входным, и выходным (`INOUT`), то необходимо вызывать как метод `setXXX`, так и метод `registerOutParameter`. Метод `setXXX` устанавливает входное значение параметра, а `registerOutParameter` регистрирует тип выходного значения.
В следующий пример демонстрирует вызов хранимой процедуры с одним `INOUT`-параметром. Метод `setByte` устанавливает значение параметра в `25`, которое будет передано хранимой процедуре базе данных как `TINYINT`. Далее метод `registerOutParameter` регистрирует первый параметр как `TINYINT`. После выполнения хранимой процедуры возвращается значение типа `TINYINT`, которое будет считано методом `getByte` в виде типа `byte`.

[source, java]
----
CallableStatement cstmt = con.prepareCall("{call procedureName(?)}");
// Определение значение параметра
cstmt.setByte(1, 25);
// Регистрация выходного параметра
cstmt.registerOutParameter(1, java.sql.Types.TINYINT);
cstmt.executeUpdate();
// Чтение параметра
byte x = cstmt.getByte(1);
----

Если хранимая процедура оформлена функцией, т.е возвращает значение не через параметры, а через оператор `RETURNS`, то для вызова используйте `execute` вместо `executeUpdate`.

== Закрытие объекта `CallableStatement`

Так же, как нужно закрывать объект `Statement`, по той же причине необходимо закрывать объект `CallableStatement`.

Простой вызов метода `close()` сделает эту работу. Если сначала закрыть объект `Connection`, он также закроет объект `CallableStatement`. Однако всегда нужно явно закрывать объект `CallableStatement`, чтобы обеспечить правильную очистку.
