= Управление транзакциями

Транзакции состоят из одного или более выражений, которые после выполнения либо фиксируются (`commit`),  либо откатываются назад (`rollback`).

Для работы с танзакциями используют следующие методы:

* `commit()` - делает окончательными все изменения в БД, проделанные `SQL`-выражением, и снимает все блокировки, установленные транзакцией.
* `rollback()` - игнорирует изменения и откатывает изменения до предыдущего состояния.

При вызове этих методов текущая транзакция заканчивается и начинается другая.

Каждое новое соединение по умолчанию находится в режиме автофиксации, что означает автоматическую фиксацию транзакций после каждого запроса. В этом случае транзакция состоит из одного запроса. Однако, есть автофиксация запрещена, транзакция не заканчивается вполоть до явного вызовы `commit()` и `rollback()`, включая, таким образом, все выражения, выполненые с момента последего завершения транзакции.

Рассмотрим следующий код:

[source, java]
----
connection.setAutoCommit(false);

//устанавливаем именнованную точку сохранения
Savepoint svpt  = connection.setSavepoint("NewEmp");

...

Statement st = connection.createStatement();

int rows = st.executeUpdate("INSERT INTO Employees " + (FirstName, LastName) VALUES " + "('Игорь','Цветков')");

rows = st.executeUpdate("UPDATE Employees set Address = 'ул.Седых.19-34'" + "WHERE LastName = 'Цветков'");
...

// Запись о работнике вставлена, но адрес не обновлен.

connection.commit(); // завершает транзакцию и подтверждаем все изменения.

}catch(SQLException e){
connection.rollback(svpt); // возвращаемся к предыдущему стабильному состоянию.
}

----


Метод `connection.setAutoCommit(false)` позволяет снять автоматическое управление транзакциями. Это означает,
что подтверждение (`commit`) и откат (`rollback`) теперь управляются в ручном режиме.

C помощью `Savepoint svpt  = connection.setSavepoint("NewEmp");` устанавливаем точку сохранения. Такая точка позволяет запомнить состояние внутри  БД и выполнить `rollback` до этого момента.

С помощью `connection.commit();` подтвеждаем завершение транзакции. Однако если во время выполнения транзакции произошел сбой, благодаря методу `connection.rollback();` находящемуся  в блоке `catch`, произойдет откат БД до предыдущего стабильного состояния. Сделать это можно так же указав точку сохранения внутри функции `connection.rollback(svpt)`, которых может быть множество.


= BATCH-команды

BATCH-команды позволяют запускать на исполнение в БД массив запросов `SQL` вместе как одну единицу. *Пример*:

[source, java]
----
st= com.createStatement();

st.addBatch("INSERT INTO...");
st.addBatch("INSERT INTO...");
st.addBatch("INSERT INTO...");

int[] updateCounts = st.executeBatch();
----

С помощью функции `addBatch()` накапливаем `SQL`-запросы и отправляем на выполнение. Следует учесть, что при возникновении исключения мы не узнает на каком именно запросе произошла ошибка. Однако, с помощью блока `try-catch` и функции `rollback()` можно вернуться до предыдущего стабильного состояния.
