= workshop-asciidoc

Workshop for theme 'AsciiDoc'

== Process

1. Клонируем репозиторий.
2. Создаем ветку согласно принятому подходу
* если используется система управления проектами (или система отслеживания ошибок), тогда использовать паттерн `${PROJECT_CODE}-${NUMBER_TASK}`, где `${PROJECT_CODE}` - буквенный код проекта, `${NUMBER_TASK}` - номер задачи в проекте;
* во всех остальных случаях использовать паттерн `feature-${SURNAME}`, где `${SURNAME}` - фамилия на английском языке.
3. Создаем документацию по теме (adoc + images):
* использовать заголовок первого уровня для названия темы статьи
* выделяем определения или важные термины жирным шрифтом;
* выделяем названия переменных, методов, значений как код;
* удаляем не существенный текст (например: "в следующей теме мы познакомимся с ..." и т.д.), т.е. текст который не помогает раскрыть текущую тему;
* даем названия для изображений, что бы они отражали суть того, что на них изображено;
* добавляем адекватный альтернативный текст для изображений. Альтернативный текст - это текст, который будет отображен, когда изображение не сможет загрузиться;
4. Фиксируем изменения в локальном репозитории.
5. Добавляем ссылку на файл в `index.adoc`.
6. Фиксируем изменения в локальном репозитории.
7. Удаляем все файлы и ссылки связанные с примером:
* документацию
* изображение
* ссылку в `index.adoc`
8. Фиксируем изменения в локальном репозитории.
9. Загружаем изменения в удаленный репозиторий.
10. Создаем запрос на слияние.
11. Ожидаем необходимого количества подтверждений от команд:
* если кто-то указал на ошибку, то исправляем ее.
12. Делаем слияние `feature` ветки в `develop`:
* если возник конфликт слияние, то решаем его.
13. Проверяем результат, перейдя на развернутую страницу сайта.

== Mistakes

* Отсутствие отступа в одну строчку от заголовка:

** Bad

----
=== Стилизация CSS
Стилизация элемента через *CSS* производится также, как и стилизация любого другого элемента.
----

** Good

----
=== Стилизация CSS

Стилизация элемента через *CSS* производится также, как и стилизация любого другого элемента.
----

* Избыточный отступ между элементами списка:

** Bad

----
* `connectedCallback`: вызывается каждый раз, когда кастомный элемент html добавляется в DOM.

* `disconnectedCallback`: вызывается каждый раз, когда кастомный элемент html удаляется из DOM.
----

** Good

----
* `connectedCallback`: вызывается каждый раз, когда кастомный элемент html добавляется в DOM.
* `disconnectedCallback`: вызывается каждый раз, когда кастомный элемент html удаляется из DOM.
----

* Выделение посторонних символов:

** Bad

    *Деление:*

** Good

    *Деление*:

* Некорректное выделение:

** Bad

    `NaN (Not a Number)` // Not a Number - термин, NaN - исходный код
    `spread-оператор` // это термин, а не исходный код

** Good

    `NaN` (*Not a Number*)
    *spread-оператор*

* Результат программы указывать в самой программе:

** Bad

    var income = 100;
    var strIncome = "100";
    var result = income == strIncome;
    console.log(result); //true

** Good

    var income = 100;
    var strIncome = "100";
    var result = income == strIncome;
    console.log(result);

    true

* Не экранировать символы, которые являются служебными для данного фреймворка

** Bad

    <=

** Good

    \<=

* Несоблюдение Code Convention для исходного кода

** Bad

    var income = 100;
    var age = 19;
    if(income<150 && age>18){
    var message = "доход больше 50";
            alert(message);
    }

** Good

    var income = 100;
    var age = 19;
    if (income < 150 && age > 18) {
        var message = "доход больше 50";
        alert(message);
    }

* Написание аббревиатур и имен собственных с маленькой буквы

** Bad

    css, html, javascript

** Good

    CSS, HTML, JavaScript
    
* Использование местоимений связанных с персоной или указывающих на принадлежность персоне

** Bad

    `HEAD` – это указатель на коммит в вашем репозитории, который станет родителем следующего коммита.
    
** Good

    `HEAD` – это указатель на коммит в репозитории, который станет родителем следующего коммита.

* Написание interfaces, classes и т.д. в одном блоке кода

** Bad

    [source,java]
    ----
    interface A {
        default void showDefault() {
            System.out.println("A: default method show()");
        }
    }
    // ...
    public class B {
        public void showDefault() {
            System.out.println("B: method show()");
        }
    }
    ----

** Good

    [source,java]
    ----
    interface A {
        default void showDefault() {
            System.out.println("A: default method show()");
        }
    }
    ----

    [source,java]
    ----
    public class B {
        public void showDefault() {
            System.out.println("B: method show()");
        }
    }
    ----
